FROM postgres:9.6

# By default the docker looks at the .env file for the following entries:
# --------------
# POSTGRES_DB=trambooline
# POSTGRES_USER=raindrop
# POSTGRES_PASSWORD=raindrop
# ----------------
# These entries ensure that the container database at least contains a bardo user with pw bard and a databse called bardo
